version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: stock_postgres
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: